# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170823_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('datasheet_name',),
            },
        ),
        migrations.CreateModel(
            name='Datasheetapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasheet_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='dataadmin',
            name='datasheet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Datasheetapp'),
        ),
    ]
