# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170825_0540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dataadmin',
            new_name='Data_admin',
        ),
        migrations.RenameModel(
            old_name='Datasheetapp',
            new_name='Datasheet_app',
        ),
    ]
