# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=120)),
                ('last_trade_date', models.DateTimeField()),
                ('strike', models.DecimalField(decimal_places=2, max_digits=20)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ask', models.DecimalField(decimal_places=2, max_digits=20)),
                ('change', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percentage_change', models.CharField(max_length=120)),
                ('volume', models.IntegerField()),
                ('open_interest', models.IntegerField()),
                ('implied_volatility', models.CharField(max_length=120)),
            ],
        ),
    ]
