# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 08:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0007_auto_20170821_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='last_edit',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 8, 26, 14, 409907, tzinfo=utc), verbose_name='last edit date'),
        ),
    ]
