# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('datasheet', '0010_auto_20170824_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='last_edit',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 10, 10, 35, 14, 489281, tzinfo=utc), verbose_name='last edit date'),
        ),
    ]
